---
- name: Ensure Python & pip present (Debian/Ubuntu)
  apt:
    name:
      - python3
      - python3-venv
      - python3-pip
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure basic tools present
  package:
    name:
      - curl
      - jq
    state: present
